### PR TITLE
template_base.html: Update jquery, popper, and bootstrap

### PR DESCRIPTION
**Pull request by MasonT8198**

### CODE REVIEW

**Comment by j8r** [comment]
Tested locally with the commit just before this one. This one has broken the burger menu on mobile: clicking on it doesn't do anything.

**Comment by j8r** [comment]
Tested locally with the commit just before this one. This one has broken the burger menu on mobile: clicking on it doesn't do anything.

**Comment by mborgerson** [comment]
> Tested locally with the commit just before this one. This one has broken the burger menu on mobile: clicking on it doesn't do anything.

Confirmed, thanks

**Comment by MasonT8198** [comment]
It didn't have that response on my iphone! Will fix and open a new one

**Pull request merged**
